import { useCallback, useState } from "react";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { Text, View } from "react-native";
import Toast from "react-native-toast-message";
import BackButtonHeader from "../../../../components/BackButtonHeader";
import DialogBox from "../../../../components/DialogBox";
import { Button, ErrorState, LoadingState, Screen, Section, StatusBadge, Surface, useColors } from "../../../../components/ui";
import { discardDonation, getDonation } from "../../../../services/donations";
import { formatDateTime, labelFor, nutritionTotals } from "../../../../constants/domain";

export default function DonationDetail() {
  const { id } = useLocalSearchParams(); const colors = useColors(); const [donation, setDonation] = useState(null); const [error, setError] = useState(null); const [reason, setReason] = useState(""); const [showDiscard, setShowDiscard] = useState(false); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { try { setError(null); setDonation(await getDonation(id)); } catch (requestError) { setError(requestError); } }, [id]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const discard = async () => { if (!reason.trim()) return Toast.show({ type: "error", text1: "Enter a reason" }); setLoading(true); try { setDonation(await discardDonation(id, reason.trim())); setShowDiscard(false); Toast.show({ type: "success", text1: "Donation discarded" }); } catch (requestError) { Toast.show({ type: "error", text1: "Could not discard", text2: requestError.message }); } finally { setLoading(false); } };
  const totals = nutritionTotals(donation?.items);
  return <View style={{ flex: 1, backgroundColor: colors.backgroundPrimary }}><BackButtonHeader title="Donation details" />{!donation && !error ? <LoadingState /> : error ? <ErrorState message={error.message} onRetry={load} /> : <Screen><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }}><Text style={{ color: colors.textPrimary, fontSize: 24, fontWeight: "900", flex: 1 }}>Food donation</Text><StatusBadge status={donation.status} /></View><Section title="Food items">{donation.items.map((item) => <Surface key={item._id || item.name} style={{ marginBottom: 10 }}><View style={{ flexDirection: "row", justifyContent: "space-between", gap: 10 }}><View style={{ flex: 1 }}><Text style={{ color: colors.textPrimary, fontWeight: "800", fontSize: 16 }}>{item.name}</Text><Text style={{ color: colors.textSecondary, marginTop: 4 }}>{item.quantityGrams} g · {item.nutritionPer100g.calories} kcal/100 g · {item.nutritionPer100g.proteinGrams} g protein/100 g</Text></View><StatusBadge status={item.nutritionSource} /></View></Surface>)}</Section><Surface style={{ marginBottom: 18 }}><Text style={{ color: colors.textPrimary, fontWeight: "800" }}>Total: {donation.quantityKg.toFixed(2)} kg</Text><Text style={{ color: colors.textSecondary, marginTop: 5 }}>{totals.calories.toFixed(0)} kcal · {totals.protein.toFixed(1)} g protein</Text></Surface><Section title="Pickup"><Surface><Detail label="Prepared" value={formatDateTime(donation.preparedAt)} colors={colors} /><Detail label="Deadline" value={formatDateTime(donation.pickupDeadline)} colors={colors} /><Detail label="Packaging" value={labelFor(donation.packagingType)} colors={colors} /><Detail label="Coordinates" value={`${donation.location.coordinates[1]}, ${donation.location.coordinates[0]}`} colors={colors} last /></Surface></Section>{donation.discardReason ? <Surface style={{ borderColor: colors.danger, marginBottom: 18 }}><Text style={{ color: colors.danger, fontWeight: "800" }}>Discard reason</Text><Text style={{ color: colors.textPrimary, marginTop: 6 }}>{donation.discardReason}</Text></Surface> : null}{donation.status === "PENDING" ? <View style={{ gap: 10 }}><Button title="Edit donation" onPress={() => router.push({ pathname: "/(app)/donor/donations/[id]/edit", params: { id } })} /><Button title="Discard donation" variant="danger" onPress={() => setShowDiscard(true)} /></View> : null}</Screen>}<DialogBox visible={showDiscard} title="Discard donation?" message="This cannot be undone. Tell us why the food is no longer available." showInput inputValue={reason} onInputChange={setReason} inputPlaceholder="Reason" confirmText="Discard" onConfirm={discard} onCancel={() => setShowDiscard(false)} loading={loading} confirmButtonStyle={{ backgroundColor: colors.danger }} /></View>;
}

function Detail({ label, value, colors, last }) { return <View style={{ flexDirection: "row", justifyContent: "space-between", paddingVertical: 9, borderBottomWidth: last ? 0 : 1, borderBottomColor: colors.border, gap: 14 }}><Text style={{ color: colors.textSecondary }}>{label}</Text><Text style={{ color: colors.textPrimary, fontWeight: "700", flex: 1, textAlign: "right" }}>{value}</Text></View>; }
