import { useEffect, useState } from "react";
import { Text, View } from "react-native";
import BackButtonHeader from "../../../components/BackButtonHeader";
import { ErrorState, LoadingState, Screen, Surface, Title, useColors } from "../../../components/ui";
import { getMyNgo, getNutritionStatus } from "../../../services/ngos";
import { BENEFICIARY_OPTIONS } from "../../../constants/domain";

export default function NutritionDetail() {
  const colors = useColors(); const [state, setState] = useState(null); const [error, setError] = useState(null);
  useEffect(() => { getMyNgo().then(async (profile) => setState({ profile, nutrition: await getNutritionStatus(profile._id) })).catch(setError); }, []);
  return <View style={{ flex: 1, backgroundColor: colors.backgroundPrimary }}><BackButtonHeader title="Nutrition status" />{!state && !error ? <LoadingState /> : error ? <ErrorState message={error.message} /> : <Screen><Title subtitle="Delivered values reset at the start of each Asia/Kolkata operational day.">Today’s nutrition</Title><View style={{ flexDirection: "row", gap: 10, marginBottom: 18 }}><Metric label="Calorie gap" value={state.nutrition.gapCalories.toFixed(0)} colors={colors} /><Metric label="Protein gap" value={`${state.nutrition.gapProtein.toFixed(1)} g`} colors={colors} /></View><Surface style={{ marginBottom: 18 }}><Row label="Target calories" value={state.nutrition.targetCalories.toLocaleString("en-IN")} colors={colors} /><Row label="Delivered calories" value={state.nutrition.deliveredCalories.toLocaleString("en-IN")} colors={colors} /><Row label="Target protein" value={`${state.nutrition.targetProtein.toLocaleString("en-IN")} g`} colors={colors} /><Row label="Delivered protein" value={`${state.nutrition.deliveredProtein.toLocaleString("en-IN")} g`} colors={colors} /><Row label="Target source" value={state.nutrition.targetSource} colors={colors} last /></Surface><Text style={{ color: colors.textPrimary, fontSize: 18, fontWeight: "800", marginBottom: 10 }}>Beneficiary groups</Text>{state.profile.beneficiaryGroups.map((group) => <Surface key={group.category} style={{ marginBottom: 9, flexDirection: "row", justifyContent: "space-between" }}><Text style={{ color: colors.textPrimary, flex: 1 }}>{BENEFICIARY_OPTIONS.find((item) => item.value === group.category)?.label}</Text><Text style={{ color: colors.primary, fontWeight: "900" }}>{group.count}</Text></Surface>)}</Screen>}</View>;
}
function Metric({ label, value, colors }) { return <Surface style={{ flex: 1, alignItems: "center" }}><Text style={{ color: colors.primary, fontSize: 22, fontWeight: "900" }}>{value}</Text><Text style={{ color: colors.textSecondary, marginTop: 4, fontSize: 12 }}>{label}</Text></Surface>; }
function Row({ label, value, colors, last }) { return <View style={{ flexDirection: "row", justifyContent: "space-between", paddingVertical: 10, borderBottomWidth: last ? 0 : 1, borderBottomColor: colors.border }}><Text style={{ color: colors.textSecondary }}>{label}</Text><Text style={{ color: colors.textPrimary, fontWeight: "800" }}>{value}</Text></View>; }
