import { useCallback, useState } from "react";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { Text, View } from "react-native";
import Toast from "react-native-toast-message";
import BackButtonHeader from "../../../../components/BackButtonHeader";
import DialogBox from "../../../../components/DialogBox";
import { DetailRow } from "../../../../components/AdminWidgets";
import { formatDateTime, labelFor, nutritionTotals } from "../../../../constants/domain";
import { Button, ErrorState, LoadingState, Screen, Section, StatusBadge, Surface, useColors } from "../../../../components/ui";
import { discardDonation, getDonation } from "../../../../services/donations";

export default function AdminDonationDetail() {
  const { id } = useLocalSearchParams(); const colors = useColors(); const [donation, setDonation] = useState(null); const [error, setError] = useState(null); const [reason, setReason] = useState(""); const [discarding, setDiscarding] = useState(false); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { try { setError(null); setDonation(await getDonation(id)); } catch (requestError) { setError(requestError); } }, [id]); useFocusEffect(useCallback(() => { load(); }, [load]));
  const discard = async () => { if (!reason.trim()) return; setLoading(true); try { await discardDonation(id, reason); setDiscarding(false); setReason(""); Toast.show({ type: "success", text1: "Donation discarded" }); load(); } catch (requestError) { Toast.show({ type: "error", text1: requestError.message }); } finally { setLoading(false); } };
  if (!donation && !error) return <Screen><LoadingState /></Screen>; if (error) return <Screen><ErrorState message={error.message} onRetry={load} /></Screen>;
  const totals = nutritionTotals(donation.items); return <View style={{ flex: 1, backgroundColor: colors.backgroundPrimary }}><BackButtonHeader title="Donation details" /><Screen><View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 18 }}><Text style={{ color: colors.textPrimary, fontSize: 24, fontWeight: "900" }}>Donation</Text><StatusBadge status={donation.status} /></View><Section title="Donor"><Surface><DetailRow label="Name" value={donation.donorId?.name} /><DetailRow label="Email" value={donation.donorId?.email} /><DetailRow label="Phone" value={donation.donorId?.phone} last /></Surface></Section><Section title="Food snapshot">{donation.items.map((item) => <Surface key={item._id || item.name} style={{ marginBottom: 10 }}><Text style={{ color: colors.textPrimary, fontWeight: "800" }}>{item.name} · {item.quantityGrams} g</Text><Text style={{ color: colors.textSecondary, marginTop: 4 }}>{item.nutritionPer100g.calories} kcal · {item.nutritionPer100g.proteinGrams} g protein / 100 g</Text><View style={{ marginTop: 8 }}><StatusBadge status={item.nutritionSource} /></View></Surface>)}<Surface><DetailRow label="Weight" value={`${donation.quantityKg.toFixed(2)} kg`} /><DetailRow label="Calories" value={`${totals.calories.toFixed(0)} kcal`} /><DetailRow label="Protein" value={`${totals.protein.toFixed(1)} g`} last /></Surface></Section><Section title="Pickup"><Surface><DetailRow label="Prepared" value={formatDateTime(donation.preparedAt)} /><DetailRow label="Deadline" value={formatDateTime(donation.pickupDeadline)} /><DetailRow label="Packaging" value={labelFor(donation.packagingType)} /><DetailRow label="Coordinates" value={`${donation.location.coordinates[1]}, ${donation.location.coordinates[0]}`} last /></Surface></Section>{donation.discardReason ? <Surface style={{ borderColor: colors.danger, marginBottom: 18 }}><Text style={{ color: colors.danger, fontWeight: "800" }}>Discard reason</Text><Text style={{ color: colors.textPrimary, marginTop: 6 }}>{donation.discardReason}</Text></Surface> : null}{donation.status === "PENDING" ? <View style={{ gap: 10 }}><Button title="Edit pending donation" onPress={() => router.push({ pathname: "/(app)/admin/donations/[id]/edit", params: { id } })} /><Button title="Discard donation" variant="danger" onPress={() => setDiscarding(true)} /></View> : null}</Screen><DialogBox visible={discarding} title="Discard donation?" message="This removes the food from future allocation." showInput inputValue={reason} onInputChange={setReason} inputPlaceholder="Required reason" confirmText="Discard" onConfirm={discard} onCancel={() => setDiscarding(false)} loading={loading} confirmButtonStyle={{ backgroundColor: colors.danger }} /></View>;
}
