import { useMemo, useState } from "react";
import { Pressable, Text, View } from "react-native";
import { Minus } from "lucide-react-native";
import Toast from "react-native-toast-message";
import CustomPicker from "./CustomPicker";
import DateTimePickerModal from "./DateTimePickerModal";
import LocationField from "./LocationField";
import { Button, Field, FilterChips, Screen, Section, StatusBadge, Surface, Title, useColors } from "./ui";
import { PACKAGING_OPTIONS, nutritionTotals } from "../constants/domain";
import { buildDonationPayload, validateDonationItems, validateDonationLogistics } from "../constants/forms";
import { analyzeNutrition, createDonation, updateDonation } from "../services/donations";

const pad = (value) => String(value).padStart(2, "0");
const datePart = (value) => { const date = new Date(value || Date.now()); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`; };
const timePart = (value) => { const date = new Date(value || Date.now()); return `${pad(date.getHours())}:${pad(date.getMinutes())}`; };
const combine = (date, time) => new Date(`${date}T${time}:00`).toISOString();

export default function DonationForm({ donation, onSuccess }) {
  const colors = useColors(); const [step, setStep] = useState(0); const [loading, setLoading] = useState(false);
  const defaultDeadline = new Date(Date.now() + 2 * 60 * 60 * 1000);
  const [items, setItems] = useState(donation?.items?.map((item) => ({ ...item, quantityGrams: String(item.quantityGrams), donorConfirmed: false })) || [{ name: "", quantityGrams: "" }]);
  const [preparedDate, setPreparedDate] = useState(datePart(donation?.preparedAt)); const [preparedTime, setPreparedTime] = useState(timePart(donation?.preparedAt));
  const [deadlineDate, setDeadlineDate] = useState(datePart(donation?.pickupDeadline || defaultDeadline)); const [deadlineTime, setDeadlineTime] = useState(timePart(donation?.pickupDeadline || defaultDeadline));
  const [packagingType, setPackagingType] = useState(donation?.packagingType || "CLOSED_CONTAINER");
  const [location, setLocation] = useState(donation?.location || { type: "Point", coordinates: ["", ""] });
  const totals = useMemo(() => nutritionTotals(items), [items]);
  const updateItem = (index, patch) => setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));
  const validItems = validateDonationItems(items);
  const nutritionReady = items.every((item) => item.analysisStatus === "READY_FOR_CONFIRMATION" && item.donorConfirmed);

  const runAnalysis = async () => { if (!validItems) return Toast.show({ type: "error", text1: "Each item needs a name and at least 250 g" }); setLoading(true); try { const suggestions = await analyzeNutrition(items.map((item) => ({ name: item.name.trim(), quantityGrams: Number(item.quantityGrams) }))); setItems(suggestions.map((item) => ({ ...item, quantityGrams: String(item.quantityGrams) }))); setStep(1); } catch (error) { Toast.show({ type: "error", text1: "Analysis failed", text2: error.message }); } finally { setLoading(false); } };
  const validateLogistics = () => validateDonationLogistics({ preparedAt: combine(preparedDate, preparedTime), pickupDeadline: combine(deadlineDate, deadlineTime), coordinates: location.coordinates });
  const submit = async () => { const error = validateLogistics(); if (error) return Toast.show({ type: "error", text1: error }); const payload = buildDonationPayload({ items, preparedAt: combine(preparedDate, preparedTime), pickupDeadline: combine(deadlineDate, deadlineTime), packagingType, coordinates: location.coordinates }); setLoading(true); try { const result = donation?._id ? await updateDonation(donation._id, payload) : await createDonation(payload); Toast.show({ type: "success", text1: donation ? "Donation updated" : "Donation created" }); onSuccess?.(result); } catch (requestError) { Toast.show({ type: "error", text1: "Could not save donation", text2: requestError.message }); } finally { setLoading(false); } };

  return <Screen><Title subtitle={donation ? "Pending donations are re-analysed before saving." : "Add food, confirm nutrition, then set pickup details."}>{donation ? "Edit donation" : "Donate food"}</Title><FilterChips value={step} onChange={() => {}} values={["Food", "Nutrition", "Pickup", "Review"].map((label, index) => ({ label: `${index + 1}. ${label}`, value: index }))} />
    {step === 0 ? <><Section title="Food items">{items.map((item, index) => <Surface key={index} style={{ marginBottom: 12 }}><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}><Text style={{ color: colors.textPrimary, fontWeight: "800" }}>Item {index + 1}</Text>{items.length > 1 ? <Pressable onPress={() => setItems((current) => current.filter((_, i) => i !== index))}><Minus color={colors.danger} /></Pressable> : null}</View><Field label="Food name" value={item.name} onChangeText={(name) => updateItem(index, { name })} placeholder="e.g. Cooked rice" /><Field label="Weight in grams" value={String(item.quantityGrams)} onChangeText={(quantityGrams) => updateItem(index, { quantityGrams })} keyboardType="numeric" placeholder="Minimum 250" /></Surface>)}</Section><Button title="Add another item" variant="secondary" onPress={() => setItems((current) => [...current, { name: "", quantityGrams: "" }])} style={{ marginBottom: 12 }} /><Button title="Analyse nutrition" onPress={runAnalysis} loading={loading} /></> : null}
    {step === 1 ? <><Section title="Confirm nutrition">{items.map((item, index) => <Surface key={index} style={{ marginBottom: 12 }}><View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 10 }}><Text style={{ color: colors.textPrimary, fontWeight: "800", fontSize: 16 }}>{item.name}</Text>{item.nutritionSource ? <StatusBadge status={item.nutritionSource} /> : null}</View>{item.analysisStatus === "UNAVAILABLE" ? <Text style={{ color: colors.danger }}>{item.message}. Change the food name or try again later.</Text> : <><Text style={{ color: colors.textSecondary }}>{item.nutritionPer100g?.calories} kcal and {item.nutritionPer100g?.proteinGrams} g protein per 100 g</Text><Pressable onPress={() => updateItem(index, { donorConfirmed: !item.donorConfirmed })} style={{ marginTop: 14, padding: 12, borderRadius: 10, borderWidth: 1, borderColor: item.donorConfirmed ? colors.success : colors.border, backgroundColor: item.donorConfirmed ? `${colors.success}18` : colors.backgroundPrimary }}><Text style={{ color: item.donorConfirmed ? colors.success : colors.textPrimary, fontWeight: "700" }}>{item.donorConfirmed ? "✓ Nutrition confirmed" : "Tap to confirm this suggestion"}</Text></Pressable></>}</Surface>)}</Section><View style={{ flexDirection: "row", gap: 10 }}><Button title="Back" variant="secondary" onPress={() => setStep(0)} style={{ flex: 1 }} /><Button title="Pickup details" disabled={!nutritionReady} onPress={() => setStep(2)} style={{ flex: 2 }} /></View></> : null}
    {step === 2 ? <><Section title="Preparation"><View style={{ flexDirection: "row", gap: 10 }}><DateTimePickerModal mode="date" value={preparedDate} onChange={setPreparedDate} label="Prepared date" /><DateTimePickerModal mode="time" value={preparedTime} onChange={setPreparedTime} label="Prepared time" /></View></Section><Section title="Pickup deadline"><View style={{ flexDirection: "row", gap: 10 }}><DateTimePickerModal mode="date" value={deadlineDate} onChange={setDeadlineDate} label="Deadline date" disablePastDates /><DateTimePickerModal mode="time" value={deadlineTime} onChange={setDeadlineTime} label="Deadline time" /></View></Section><Section title="Packaging"><CustomPicker data={PACKAGING_OPTIONS} value={packagingType} onChange={(item) => setPackagingType(item.value)} placeholder="Packaging type" searchPlaceholder="" /></Section><LocationField value={location} onChange={setLocation} /><View style={{ flexDirection: "row", gap: 10, marginTop: 16 }}><Button title="Back" variant="secondary" onPress={() => setStep(1)} style={{ flex: 1 }} /><Button title="Review" onPress={() => { const error = validateLogistics(); if (error) Toast.show({ type: "error", text1: error }); else setStep(3); }} style={{ flex: 2 }} /></View></> : null}
    {step === 3 ? <><Surface style={{ marginBottom: 16 }}><Text style={{ color: colors.textPrimary, fontSize: 19, fontWeight: "800", marginBottom: 12 }}>{items.length} food item{items.length === 1 ? "" : "s"}</Text>{items.map((item) => <Text key={item.name} style={{ color: colors.textSecondary, marginBottom: 5 }}>{item.name} · {item.quantityGrams} g</Text>)}<View style={{ height: 1, backgroundColor: colors.border, marginVertical: 12 }} /><Text style={{ color: colors.textPrimary, fontWeight: "700" }}>{totals.calories.toFixed(0)} kcal · {totals.protein.toFixed(1)} g protein</Text><Text style={{ color: colors.textSecondary, marginTop: 8 }}>Pickup deadline: {new Date(combine(deadlineDate, deadlineTime)).toLocaleString("en-IN")}</Text><Text style={{ color: colors.textSecondary, marginTop: 4 }}>Packaging: {PACKAGING_OPTIONS.find((item) => item.value === packagingType)?.label}</Text></Surface><View style={{ flexDirection: "row", gap: 10 }}><Button title="Back" variant="secondary" onPress={() => setStep(2)} style={{ flex: 1 }} /><Button title={donation ? "Save changes" : "Submit donation"} loading={loading} onPress={submit} style={{ flex: 2 }} /></View></> : null}
  </Screen>;
}
